apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: qcloud
  name: ing-1
  namespace: default
spec:
  rules:
  - host: domain.test
    http:
      paths:
      - backend:
          serviceName: svc-np-1
          servicePort: 80
        path: /