apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-1-deployment
  labels:
    app: node-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-1
  template:
    metadata:
      labels:
        app: node-app-1
    spec:
      containers:
      - name: node-app-1
        image: hhhtj/node-app-1
        imagePullPolicy: Never
        ports:
        - containerPort: 8888